
'''
This is my main file to run all things are connected mainly with this
The Database System has not implimented Yet

Just For Testing For Rana Universe
Any Sugesstion Please Contact 🍌🍌🍌
For Mail: RanaUniverse321@gmail.com
Message Me: https://t.me/RanaUniverse

'''

import sys
sys.dont_write_bytecode = True



from telegram import Update
from telegram.ext import Application
from telegram.ext import ContextTypes
from telegram.ext import CommandHandler, MessageHandler, filters

from telegram.ext import ContextTypes
from telegram.constants import ParseMode


'''
Rana Universe 🍌🍌🍌
Rana Universe 🍌🍌🍌
Rana Universe 🍌🍌🍌
Below will my special coding started
Rana Universe 🍌🍌🍌
Rana Universe 🍌🍌🍌
Rana Universe 🍌🍌🍌
'''


import random
async def get_user_name_design(user, context: ContextTypes.DEFAULT_TYPE):
    '''Pass the user = update.message.from_user like this and it will get the name and return after makeup'''
    full_name = user.full_name
    designs = [
        f"1 Your Name is:\n\n<b>{full_name}</b>\n\n",
        f"2 Your Name is:\n\n<strong>{full_name}</strong>\n\n",
        f"3 Your Name is:\n\n<i>{full_name}</i>\n\n",
        f"4 Your Name is:\n\n<em>{full_name}</em>\n\n",
        f"5 Your Name is:\n\n<u>{full_name}</u>\n\n",
        f"6 Your Name is:\n\n<ins>{full_name}</ins>\n\n",
        f"7 Your Name is:\n\n<s>{full_name}</s>\n\n",
        f"8 Your Name is:\n\n<strike>{full_name}</strike>\n\n",
        f"9 Your Name is:\n\n<del>{full_name}</del>\n\n",
        f"10 Your Name is:\n\n<span class='tg-spoiler'>{full_name}</span>\n\n",
        f"11 Your Name is: \n\n<tg-spoiler>{full_name}</tg-spoiler>\n\n",
        f"12 Your Name is:\n\n<b>{full_name} <i>italic {full_name}</i></b>\n\n",
        f"13 Your Name is:\n\n<a href='http://t.me/@{user.username}/'>{full_name}</a>\n\n",
        f"14 Your Name is:\n\n<a href='tg://user?id=1895194333'>{full_name}</a>\n\n",
        f"15 Your Name is:\n\n<tg-emoji emoji-id='5368324170671202286'>{full_name}</tg-emoji>\n\n",
        f"16 Your Name is:\n\n<code>{full_name}</code>\n\n",
        f"17 Your Name is:\n\n<pre>{full_name}</pre>\n\n",
        f"18 Your Name is:\n\n<pre><code class='language-python'>{full_name}</code></pre>\n\n",
        f"19 Your Name is:\n\n<blockquote>{full_name}</blockquote>\n\n",
        f"20 Welcome, {full_name}!\n\n",
        f"21 Meet {full_name}!\n\n",
        f"22 Introducing {full_name}!\n\n",
        f"23 Presenting {full_name}!\n\n",
        f"24 Say hello to {full_name}!\n\n",
        f"25 {full_name} has arrived!\n\n",
        f"26 The one and only {full_name}!\n\n",
        f"27 Greetings from {full_name}!\n\n",
        f"28 All hail {full_name}!\n\n",
        f"29 Cheers for {full_name}!\n\n",
        f"30 Salutations, {full_name}!\n\n",
        f"31 {full_name}: The legend!\n\n",
        f"32 The marvelous {full_name}!\n\n",
        f"33 Bow down to {full_name}!\n\n",
        f"34 Let's hear it for {full_name}!\n\n",
        f"35 Hip hip hooray for {full_name}!\n\n",
        f"36 Everyone, meet {full_name}!\n\n",
        f"37 The extraordinary {full_name}!\n\n",
        f"38 The fabulous {full_name}!\n\n",
        f"39 The one and only {full_name}!\n\n",
        f"40 It's {full_name} o'clock!\n\n",
        f"41 Ready or not, here's {full_name}!\n\n",
        f"42 Make way for {full_name}!\n\n",
        f"43 {full_name}, reporting for duty!\n\n",
        f"44 Step right up, {full_name}!\n\n",
        f"45 Here comes {full_name}!\n\n",
        f"46 Make some noise for {full_name}!\n\n",
        f"47 The incredible {full_name}!\n\n",
        f"48 Raise your glasses to {full_name}!\n\n",
        f"49 Drumroll, please... {full_name}!\n\n",
        f"50 Voila! It's {full_name}!\n\n",
        f"51 Cheers to {full_name}!\n\n",
        f"52 Hey there, {full_name}!\n\n",
        f"53 Greetings, {full_name}!\n\n",
        f"54 Hi, {full_name}!\n\n",
        f"55 Nice to meet you, {full_name}!\n\n",
        f"56 Hooray for {full_name}!\n\n",
        f"57 Pleased to meet you, {full_name}!\n\n",
        f"58 Welcome aboard, {full_name}!\n\n",
        f"59 Here's {full_name}!\n\n",
        f"60 Behold, {full_name}!\n\n",
        f"61 It's {full_name} time!\n\n",
        f"62 Let's give it up for {full_name}!\n\n",
        f"63 Welcome to the party, {full_name}!\n\n",
        f"64 Make some noise, {full_name}!\n\n",
        f"65 It's party time with {full_name}!\n\n",
        f"66 Say hi to {full_name}!\n\n",
        f"67 Big cheers for {full_name}!\n\n",
        f"68 Hail to {full_name}!\n\n",
        f"69 Three cheers for {full_name}!\n\n",
        f"70 Get ready for {full_name}!\n\n",
        f"71 Hats off to {full_name}!\n\n",
        f"72 We welcome {full_name}!\n\n",
        f"73 A round of applause for {full_name}!\n\n",
        f"74 Let's welcome {full_name}!\n\n",
        f"75 All eyes on {full_name}!\n\n",
        f"76 Make it loud for {full_name}!\n\n",
        f"77 Here's a shoutout to {full_name}!\n\n",
        f"78 We salute {full_name}!\n\n",
        f"79 Shoutout to {full_name}!\n\n",
        f"80 It's time for {full_name}!\n\n",
        f"81 Here's a warm welcome to {full_name}!\n\n",
        f"82 Make some noise for {full_name}!\n\n",
        f"83 Let's rock with {full_name}!\n\n",
        f"84 It's showtime with {full_name}!\n\n",
        f"85 Here's to {full_name}!\n\n",
        f"86 A big hello to {full_name}!\n\n",
        f"87 Hip hip hooray, {full_name} is here!\n\n",
        f"88 Give it up for {full_name}!\n\n",
        f"89 Three cheers for {full_name}!\n\n",
        f"90 Here comes {full_name}, ready or not!\n\n",
        f"91 Welcome, {full_name}, with open arms!\n\n",
        f"92 Here's a round of applause for {full_name}!\n\n",
        f"93 Let's give a warm welcome to {full_name}!\n\n",
        f"94 It's {full_name}, everybody!\n\n",
        f"95 Welcome, welcome, {full_name}!\n\n",
        f"96 The stage is set for {full_name}!\n\n",
        f"97 A big hello to {full_name}, our newest member!\n\n",
        f"98 Shoutout to {full_name}, the star of the show!\n\n",
        f"99 All eyes on {full_name}, let's go!\n\n",
        f"100 Let's get the party started with {full_name}!\n\n",
        f"101 Let's give a warm welcome to {full_name}!\n\n",
        f"102 It's {full_name}, everybody!\n\n",
        f"103 Welcome, welcome, {full_name}!\n\n",
        f"104 The stage is set for {full_name}!\n\n",
        f"105 A big hello to {full_name}, our newest member!\n\n",
        f"106 Shoutout to {full_name}, the star of the show!\n\n",
        f"107 All eyes on {full_name}, let's go!\n\n",
        f"108 Let's get the party started with {full_name}!\n\n",
        f"109 Here's to {full_name}, our MVP!\n\n",
        f"110 Welcome aboard, {full_name}!\n\n",
        f"111 Say hello to {full_name}, our rockstar!\n\n",
        f"112 Cheers to {full_name}, our superstar!\n\n",
        f"113 A big shoutout to {full_name} for joining us!\n\n",
        f"114 Let's make some noise for {full_name}!\n\n",
        f"115 Here's to {full_name}, the life of the party!\n\n",
        f"116 Welcome to the team, {full_name}!\n\n",
        f"117 Let's raise a toast to {full_name}!\n\n",
        f"118 Say hello to {full_name}, our shining star!\n\n",
        f"119 A warm welcome to {full_name}!\n\n",
        f"120 Let's celebrate {full_name}!\n\n",
        f"121 Here's {full_name}, ready to dazzle!\n\n",
        f"122 Welcome, {full_name}, with open arms!\n\n",
        f"123 A big hello to {full_name}, our newest addition!\n\n",
        f"124 It's {full_name} time, let's party!\n\n",
        f"125 All hail {full_name}, our hero!\n\n",
        f"126 Say hi to {full_name}, our champion!\n\n",
        f"127 Welcome to the family, {full_name}!\n\n",
        f"128 Let's give a round of applause to {full_name}!\n\n",
        f"129 Make some noise for {full_name}, our inspiration!\n\n",
        f"130 Here's to {full_name}, our guiding light!\n\n",
        f"131 Say hello to {full_name}, our guiding force!\n\n",
        f"132 Let's welcome {full_name}, our beacon of hope!\n\n",
        f"133 A big shoutout to {full_name}, our role model!\n\n",
        f"134 Welcome, {full_name}, the heart of the team!\n\n",
        f"135 Let's give a standing ovation to {full_name}!\n\n",
        f"136 Here's to {full_name}, our driving force!\n\n",
        f"137 Say hi to {full_name}, our source of strength!\n\n",
        f"138 Welcome to the club, {full_name}!\n\n",
        f"139 Let's celebrate {full_name}, our motivator!\n\n",
        f"140 Here's {full_name}, our mentor!\n\n",
        f"141 All hail {full_name}, our guru!\n\n",
        f"142 Say hello to {full_name}, our teacher!\n\n",
        f"143 Let's welcome {full_name}, our guide!\n\n",
        f"144 Here's to {full_name}, our coach!\n\n",
        f"145 Welcome, {full_name}, our leader!\n\n",
        f"146 Let's give a round of applause to {full_name}, our captain!\n\n",
        f"147 Make some noise for {full_name}, our commander!\n\n",
        f"148 Here's to {full_name}, our director!\n\n",
        f"149 Say hello to {full_name}, our manager!\n\n",
        f"150 Let's welcome {full_name}, our supervisor!\n\n",
        f"151 Here's {full_name}, our executive!\n\n",
        f"152 All hail {full_name}, our CEO!\n\n",
        f"153 Say hi to {full_name}, our president!\n\n",
        f"154 Welcome to the board, {full_name}!\n\n",
        f"155 Let's celebrate {full_name}, our chairman!\n\n",
        f"156 Here's to {full_name}, our founder!\n\n",
        f"157 Say hello to {full_name}, our visionary!\n\n",
        f"158 Let's welcome {full_name}, our innovator!\n\n",
        f"159 Here's {full_name}, our trailblazer!\n\n",
        f"160 All hail {full_name}, our pioneer!\n\n",
        f"161 Say hi to {full_name}, our inventor!\n\n",
        f"162 Welcome to the team, {full_name}, our creator!\n\n",
        f"163 Let's celebrate {full_name}, our artist!\n\n",
        f"164 Here's to {full_name}, our designer!\n\n",
        f"165 Say hello to {full_name}, our architect!\n\n",
        f"166 Let's welcome {full_name}, our engineer!\n\n",
        f"167 Here's {full_name}, our developer!\n\n",
        f"168 All hail {full_name}, our programmer!\n\n",
        f"169 Say hi to {full_name}, our coder!\n\n",
        f"170 Welcome to the team, {full_name}, our hacker!\n\n",
        f"171 Let's celebrate {full_name}, our analyst!\n\n",
        f"172 Here's to {full_name}, our strategist!\n\n",
        f"173 Say hello to {full_name}, our planner!\n\n",
        f"174 Let's welcome {full_name}, our organizer!\n\n",
        f"175 Here's {full_name}, our coordinator!\n\n",
        f"176 All hail {full_name}, our manager!\n\n",
        f"177 Say hi to {full_name}, our leader!\n\n",
        f"178 Welcome to the team, {full_name}, our supervisor!\n\n",
        f"179 Let's celebrate {full_name}, our director!\n\n",
        f"180 Here's to {full_name}, our executive!\n\n",
        f"181 Say hello to {full_name}, our CEO!\n\n",
        f"182 Let's welcome {full_name}, our president!\n\n",
        f"183 Here's {full_name}, our chairman!\n\n",
        f"184 All hail {full_name}, our founder!\n\n",
        f"185 Say hi to {full_name}, our visionary!\n\n",
        f"186 Welcome to the team, {full_name}, our innovator!\n\n",
        f"187 Let's celebrate {full_name}, our trailblazer!\n\n",
        f"188 Here's to {full_name}, our pioneer!\n\n",
        f"189 Say hello to {full_name}, our inventor!\n\n",
        f"190 Let's welcome {full_name}, our creator!\n\n",
        f"191 Here's {full_name}, our artist!\n\n",
        f"192 All hail {full_name}, our designer!\n\n",
        f"193 Say hi to {full_name}, our architect!\n\n",
        f"194 Welcome to the team, {full_name}, our engineer!\n\n",
        f"195 Let's celebrate {full_name}, our developer!\n\n",
        f"196 Here's to {full_name}, our programmer!\n\n",
        f"197 Say hello to {full_name}, our coder!\n\n",
        f"198 Let's welcome {full_name}, our hacker!\n\n",
        f"199 Here's {full_name}, our analyst!\n\n",
        f"200 All hail {full_name}, our strategist!\n\n",
        f"201 Say hi to {full_name}, our planner!\n\n",
        f"202 Welcome to the team, {full_name}, our organizer!\n\n",
        f"203 Let's celebrate {full_name}, our coordinator!\n\n",
        f"204 Here's to {full_name}, our manager!\n\n",
        f"205 Say hello to {full_name}, our leader!\n\n",
        f"206 Let's welcome {full_name}, our supervisor!\n\n",
        f"207 Here's {full_name}, our director!\n\n",
        f"208 All hail {full_name}, our executive!\n\n",
        f"209 Say hi to {full_name}, our CEO!\n\n",
        f"210 Welcome to the team, {full_name}, our president!\n\n",
        f"211 Let's celebrate {full_name}, our chairman!\n\n",
        f"212 Here's to {full_name}, our founder!\n\n",
        f"213 Say hello to {full_name}, our CEO!\n\n",
        f"214 Let's welcome {full_name}, our president!\n\n",
        f"215 Here's {full_name}, our chairman!\n\n",
        f"216 All hail {full_name}, our founder!\n\n",
        f"217 Say hi to {full_name}, our visionary!\n\n",
        f"218 Welcome to the team, {full_name}, our innovator!\n\n",
        f"219 Let's celebrate {full_name}, our trailblazer!\n\n",
        f"220 Here's to {full_name}, our pioneer!\n\n",
        f"221 Say hello to {full_name}, our inventor!\n\n",
        f"222 Let's welcome {full_name}, our creator!\n\n",
        f"223 Here's {full_name}, our artist!\n\n",
        f"224 All hail {full_name}, our designer!\n\n",
        f"225 Say hi to {full_name}, our architect!\n\n",
        f"226 Welcome to the team, {full_name}, our engineer!\n\n",
        f"227 Let's celebrate {full_name}, our developer!\n\n",
        f"228 Here's to {full_name}, our programmer!\n\n",
        f"229 Say hello to {full_name}, our coder!\n\n",
        f"230 Let's welcome {full_name}, our hacker!\n\n",
        f"231 Here's {full_name}, our analyst!\n\n",
        f"232 All hail {full_name}, our strategist!\n\n",
        f"233 Say hi to {full_name}, our planner!\n\n",
        f"234 Welcome to the team, {full_name}, our organizer!\n\n",
        f"235 Let's celebrate {full_name}, our coordinator!\n\n",
        f"236 Here's to {full_name}, our manager!\n\n",
        f"237 Say hello to {full_name}, our leader!\n\n",
        f"238 Let's welcome {full_name}, our supervisor!\n\n",
        f"239 Here's {full_name}, our director!\n\n",
        f"240 All hail {full_name}, our executive!\n\n",
        f"241 Say hi to {full_name}, our CEO!\n\n",
        f"242 Welcome to the team, {full_name}, our president!\n\n",
        f"243 Let's celebrate {full_name}, our chairman!\n\n",
        f"244 Here's to {full_name}, our founder!\n\n",
        f"245 Say hello to {full_name}, our visionary!\n\n",
        f"246 Let's welcome {full_name}, our innovator!\n\n",
        f"247 Here's {full_name}, our trailblazer!\n\n",
        f"248 Say hi to {full_name}, our pioneer!\n\n",
        f"249 Let's welcome {full_name}, our inventor!\n\n",
        f"250 Here's {full_name}, our creator!\n\n",
        f"251 All hail {full_name}, our artist!\n\n",
        f"252 Say hi to {full_name}, our designer!\n\n",
        f"253 Welcome to the team, {full_name}, our architect!\n\n",
        f"254 Let's celebrate {full_name}, our engineer!\n\n",
        f"255 Here's to {full_name}, our developer!\n\n",
        f"256 Say hello to {full_name}, our programmer!\n\n",
        f"257 Let's welcome {full_name}, our coder!\n\n",
        f"258 Here's {full_name}, our hacker!\n\n",
        f"259 All hail {full_name}, our analyst!\n\n",
        f"260 Say hi to {full_name}, our strategist!\n\n",
        f"261 Welcome to the team, {full_name}, our planner!\n\n",
        f"262 Let's celebrate {full_name}, our organizer!\n\n",
        f"263 Here's to {full_name}, our coordinator!\n\n",
        f"264 Say hello to {full_name}, our manager!\n\n",
        f"265 Let's welcome {full_name}, our leader!\n\n",
        f"266 Here's {full_name}, our supervisor!\n\n",
        f"267 All hail {full_name}, our director!\n\n",
        f"268 Say hi to {full_name}, our executive!\n\n",
        f"269 Welcome to the team, {full_name}, our CEO!\n\n",
        f"270 Let's celebrate {full_name}, our president!\n\n",
        f"271 Here's to {full_name}, our chairman!\n\n",
        f"272 Say hello to {full_name}, our founder!\n\n",
        f"273 Let's welcome {full_name}, our visionary!\n\n",
        f"274 Here's {full_name}, our innovator!\n\n",
        f"275 Say hi to {full_name}, our trailblazer!\n\n",
        f"276 Let's welcome {full_name}, our pioneer!\n\n",
        f"277 Here's {full_name}, our inventor!\n\n",
        f"278 All hail {full_name}, our creator!\n\n",
        f"279 Say hi to {full_name}, our artist!\n\n",
        f"280 Welcome to the team, {full_name}, our designer!\n\n",
        f"281 Let's celebrate {full_name}, our architect!\n\n",
        f"282 Here's to {full_name}, our engineer!\n\n",
        f"283 Say hello to {full_name}, our developer!\n\n",
        f"284 Let's welcome {full_name}, our programmer!\n\n",
        f"285 Here's {full_name}, our coder!\n\n",
        f"286 All hail {full_name}, our hacker!\n\n",
        f"287 Say hi to {full_name}, our analyst!\n\n",
        f"288 Welcome to the team, {full_name}, our strategist!\n\n",
        f"289 Let's celebrate {full_name}, our planner!\n\n",
        f"290 Here's to {full_name}, our organizer!\n\n",
        f"291 Say hello to {full_name}, our coordinator!\n\n",
        f"292 Let's welcome {full_name}, our manager!\n\n",
        f"293 Here's {full_name}, our leader!\n\n",
        f"294 All hail {full_name}, our supervisor!\n\n",
        f"295 Say hi to {full_name}, our director!\n\n",
        f"296 Welcome to the team, {full_name}, our executive!\n\n",
        f"297 Let's celebrate {full_name}, our CEO!\n\n",
        f"298 Here's to {full_name}, our president!\n\n",
        f"299 Say hello to {full_name}, our chairman!\n\n",
        f"300 Let's welcome {full_name}, our founder!\n\n",
        f"301 Here's {full_name}, our visionary!\n\n",
        f"302 All hail {full_name}, our innovator!\n\n",
        f"303 Say hi to {full_name}, our trailblazer!\n\n",
        f"304 Let's welcome {full_name}, our pioneer!\n\n",
        f"305 Here's {full_name}, our inventor!\n\n",
        f"306 All hail {full_name}, our creator!\n\n",
        f"307 Say hi to {full_name}, our artist!\n\n",
        f"308 Welcome to the team, {full_name}, our designer!\n\n",
        f"309 Let's celebrate {full_name}, our architect!\n\n",
        f"310 Here's to {full_name}, our engineer!\n\n",
        f"311 Say hello to {full_name}, our developer!\n\n",
        f"312 Let's welcome {full_name}, our programmer!\n\n",
        f"313 Here's {full_name}, our coder!\n\n",
        f"314 All hail {full_name}, our hacker!\n\n",
        f"315 Say hi to {full_name}, our analyst!\n\n",
        f"316 Welcome to the team, {full_name}, our strategist!\n\n",
        f"317 Let's celebrate {full_name}, our planner!\n\n",
        f"318 Here's to {full_name}, our organizer!\n\n",
        f"319 Say hello to {full_name}, our coordinator!\n\n",
        f"320 Let's welcome {full_name}, our manager!\n\n",
        f"321 Here's {full_name}, our leader!\n\n",
        f"322 All hail {full_name}, our supervisor!\n\n",
        f"323 Say hi to {full_name}, our director!\n\n",
        f"324 Welcome to the team, {full_name}, our executive!\n\n",
        f"325 Let's celebrate {full_name}, our CEO!\n\n",
        f"326 Here's to {full_name}, our president!\n\n",
        f"327 Say hello to {full_name}, our chairman!\n\n",
        f"328 Let's welcome {full_name}, our founder!\n\n",
        f"329 Here's {full_name}, our visionary!\n\n",
        f"330 All hail {full_name}, our innovator!\n\n",
        f"331 Say hi to {full_name}, our trailblazer!\n\n",
        f"332 Let's welcome {full_name}, our pioneer!\n\n",
        f"333 Here's {full_name}, our inventor!\n\n",
        f"334 All hail {full_name}, our creator!\n\n",
        f"335 Say hi to {full_name}, our artist!\n\n",
        f"336 Welcome to the team, {full_name}, our designer!\n\n",
        f"337 Let's celebrate {full_name}, our architect!\n\n",
        f"338 Here's to {full_name}, our engineer!\n\n",
        f"339 Say hello to {full_name}, our developer!\n\n",
        f"340 Let's welcome {full_name}, our programmer!\n\n",
        f"341 Here's {full_name}, our coder!\n\n",
        f"342 All hail {full_name}, our hacker!\n\n",
        f"343 Say hi to {full_name}, our analyst!\n\n",
        f"344 Welcome to the team, {full_name}, our strategist!\n\n",
        f"345 Let's celebrate {full_name}, our planner!\n\n",
        f"346 Here's to {full_name}, our organizer!\n\n",
        f"347 Say hello to {full_name}, our coordinator!\n\n",
        f"348 Let's welcome {full_name}, our manager!\n\n",
        f"349 Here's {full_name}, our leader!\n\n",
        f"350 All hail {full_name}, our supervisor!\n\n",
        f"351 Say hi to {full_name}, our director!\n\n",
        f"352 Welcome to the team, {full_name}, our executive!\n\n",
        f"353 Let's celebrate {full_name}, our CEO!\n\n",
        f"354 Here's to {full_name}, our president!\n\n",
        f"355 Say hello to {full_name}, our chairman!\n\n",
        f"356 Let's welcome {full_name}, our founder!\n\n",
        f"357 Here's {full_name}, our visionary!\n\n",
        f"358 All hail {full_name}, our innovator!\n\n",
        f"359 Say hi to {full_name}, our trailblazer!\n\n",
        f"360 Let's welcome {full_name}, our pioneer!\n\n",
        f"361 Here's {full_name}, our inventor!\n\n",
        f"362 All hail {full_name}, our creator!\n\n",
        f"363 Say hi to {full_name}, our artist!\n\n",
        f"364 Welcome to the team, {full_name}, our designer!\n\n",
        f"365 Let's celebrate {full_name}, our architect!\n\n",
        f"366 Here's to {full_name}, our engineer!\n\n",
        f"367 Say hello to {full_name}, our developer!\n\n",
        f"368 Let's welcome {full_name}, our programmer!\n\n",
        f"369 Here's {full_name}, our coder!\n\n",
        f"370 All hail {full_name}, our hacker!\n\n",
        f"371 Say hi to {full_name}, our analyst!\n\n",
        f"372 Welcome to the team, {full_name}, our strategist!\n\n",
        f"373 Let's celebrate {full_name}, our planner!\n\n",
        f"374 Here's to {full_name}, our organizer!\n\n",
        f"375 Say hello to {full_name}, our coordinator!\n\n",
        f"376 Let's welcome {full_name}, our manager!\n\n",
        f"377 Here's {full_name}, our leader!\n\n",
        f"378 All hail {full_name}, our supervisor!\n\n",
        f"379 Say hi to {full_name}, our director!\n\n",
        f"380 Welcome to the team, {full_name}, our executive!\n\n",
        f"381 Let's celebrate {full_name}, our CEO!\n\n",
        f"382 Here's to {full_name}, our president!\n\n",
        f"383 Say hello to {full_name}, our chairman!\n\n",
        f"384 Let's welcome {full_name}, our founder!\n\n",
        f"385 Here's {full_name}, our visionary!\n\n",
        f"386 All hail {full_name}, our innovator!\n\n",
        f"387 Say hi to {full_name}, our trailblazer!\n\n",
        f"388 Let's welcome {full_name}, our pioneer!\n\n",
        f"389 Here's {full_name}, our inventor!\n\n",
        f"390 All hail {full_name}, our creator!\n\n",
        f"391 Say hi to {full_name}, our artist!\n\n",
        f"392 Welcome to the team, {full_name}, our designer!\n\n",
        f"393 Let's celebrate {full_name}, our architect!\n\n",
        f"394 Here's to {full_name}, our engineer!\n\n",
        f"395 Say hello to {full_name}, our developer!\n\n",
        f"396 Let's welcome {full_name}, our programmer!\n\n",
        f"397 Here's {full_name}, our coder!\n\n",
        f"398 All hail {full_name}, our hacker!\n\n",
        f"399 Say hi to {full_name}, our analyst!\n\n",
        f"400 Welcome to the team, {full_name}, our strategist!\n\n",
        f"401 Let's celebrate {full_name}, our planner!\n\n",
        f"402 Here's to {full_name}, our organizer!\n\n",
        f"403 Say hello to {full_name}, our coordinator!\n\n",
        f"404 Let's welcome {full_name}, our manager!\n\n",
        f"405 Here's {full_name}, our leader!\n\n",
        f"406 All hail {full_name}, our supervisor!\n\n",
        f"407 Say hi to {full_name}, our director!\n\n",
        f"408 Welcome to the team, {full_name}, our executive!\n\n",
        f"409 Let's celebrate {full_name}, our CEO!\n\n",
        f"410 Here's to {full_name}, our president!\n\n",
        f"411 Say hello to {full_name}, our chairman!\n\n",
        f"412 Let's welcome {full_name}, our founder!\n\n",
        f"413 Here's {full_name}, our visionary!\n\n",
        f"414 All hail {full_name}, our innovator!\n\n",
        f"415 Say hi to {full_name}, our trailblazer!\n\n",
        f"416 Let's welcome {full_name}, our pioneer!\n\n",
        f"417 Here's {full_name}, our inventor!\n\n",
        f"418 All hail {full_name}, our creator!\n\n",
        f"419 Say hi to {full_name}, our artist!\n\n",
        f"420 Welcome to the team, {full_name}, our designer!\n\n",
        f"421 Let's celebrate {full_name}, our architect!\n\n",
        f"422 Here's to {full_name}, our engineer!\n\n",
        f"423 Say hello to {full_name}, our developer!\n\n",
        f"424 Let's welcome {full_name}, our programmer!\n\n",
        f"425 Here's {full_name}, our coder!\n\n",
        f"426 All hail {full_name}, our hacker!\n\n",
        f"427 Say hi to {full_name}, our analyst!\n\n",
        f"428 Welcome to the team, {full_name}, our strategist!\n\n",
        f"429 Let's celebrate {full_name}, our planner!\n\n",
        f"430 Here's to {full_name}, our organizer!\n\n",
        f"431 Say hello to {full_name}, our coordinator!\n\n",
        f"432 Let's welcome {full_name}, our manager!\n\n",
        f"433 Here's {full_name}, our leader!\n\n",
        f"434 All hail {full_name}, our supervisor!\n\n",
        f"435 Say hi to {full_name}, our director!\n\n",
        f"436 Welcome to the team, {full_name}, our executive!\n\n",
        f"437 Let's celebrate {full_name}, our CEO!\n\n",
        f"438 Here's to {full_name}, our president!\n\n",
        f"439 Say hello to {full_name}, our chairman!\n\n",
        f"440 Let's welcome {full_name}, our founder!\n\n",
        f"441 Here's {full_name}, our visionary!\n\n",
        f"442 All hail {full_name}, our innovator!\n\n",
        f"443 Say hi to {full_name}, our trailblazer!\n\n",
        f"444 Let's welcome {full_name}, our pioneer!\n\n",
        f"445 Here's {full_name}, our inventor!\n\n",
        f"446 All hail {full_name}, our creator!\n\n",
        f"447 Say hi to {full_name}, our artist!\n\n",
        f"448 Welcome to the team, {full_name}, our designer!\n\n",
        f"449 Let's celebrate {full_name}, our architect!\n\n",
        f"450 Here's to {full_name}, our engineer!\n\n",
        f"451 Say hello to {full_name}, our developer!\n\n",
        f"452 Let's welcome {full_name}, our programmer!\n\n",
        f"453 Here's {full_name}, our coder!\n\n",
        f"454 All hail {full_name}, our hacker!\n\n",
        f"455 Say hi to {full_name}, our analyst!\n\n",
        f"456 Welcome to the team, {full_name}, our strategist!\n\n",
        f"457 Let's celebrate {full_name}, our planner!\n\n",
        f"458 Here's to {full_name}, our organizer!\n\n",
        f"459 Say hello to {full_name}, our coordinator!\n\n",
        f"460 Let's welcome {full_name}, our manager!\n\n",
        f"461 Here's {full_name}, our leader!\n\n",
        f"462 All hail {full_name}, our supervisor!\n\n",
        f"463 Say hi to {full_name}, our director!\n\n",
        f"464 Welcome to the team, {full_name}, our executive!\n\n",
        f"465 Let's celebrate {full_name}, our CEO!\n\n",
        f"466 Here's to {full_name}, our president!\n\n",
        f"467 Say hello to {full_name}, our chairman!\n\n",
        f"468 Let's welcome {full_name}, our founder!\n\n",
        f"469 Here's {full_name}, our visionary!\n\n",
        f"470 All hail {full_name}, our innovator!\n\n",
        f"471 Say hi to {full_name}, our trailblazer!\n\n",
        f"472 Let's welcome {full_name}, our pioneer!\n\n",
        f"473 Here's {full_name}, our inventor!\n\n",
        f"474 All hail {full_name}, our creator!\n\n",
        f"475 Say hi to {full_name}, our artist!\n\n",
        f"476 Welcome to the team, {full_name}, our designer!\n\n",
        f"477 Let's celebrate {full_name}, our architect!\n\n",
        f"478 Here's to {full_name}, our engineer!\n\n",
        f"479 Say hello to {full_name}, our developer!\n\n",
        f"480 Let's welcome {full_name}, our programmer!\n\n",
        f"481 Here's {full_name}, our coder!\n\n",
        f"482 All hail {full_name}, our hacker!\n\n",
        f"483 Say hi to {full_name}, our analyst!\n\n",
        f"484 Welcome to the team, {full_name}, our strategist!\n\n",
        f"485 Let's celebrate {full_name}, our planner!\n\n",
        f"486 Here's to {full_name}, our organizer!\n\n",
        f"487 Say hello to {full_name}, our coordinator!\n\n",
        f"488 Let's welcome {full_name}, our manager!\n\n",
        f"489 Here's {full_name}, our leader!\n\n",
        f"490 All hail {full_name}, our supervisor!\n\n",
        f"491 Say hi to {full_name}, our director!\n\n",
        f"492 Welcome to the team, {full_name}, our executive!\n\n",
        f"493 Let's celebrate {full_name}, our CEO!\n\n",
        f"494 Here's to {full_name}, our president!\n\n",
        f"495 Say hello to {full_name}, our chairman!\n\n",
        f"496 Let's welcome {full_name}, our founder!\n\n",
        f"497 Here's {full_name}, our visionary!\n\n",
        f"498 All hail {full_name}, our innovator!\n\n",
        f"499 Say hi to {full_name}, our trailblazer!\n\n",
        f"500 Let's welcome {full_name}, our pioneer!\n\n",
        f"501 Here's {full_name}, our inventor!\n\n",
        f"502 All hail {full_name}, our creator!\n\n",
        f"503 Say hi to {full_name}, our artist!\n\n",
        f"504 Welcome to the team, {full_name}, our designer!\n\n",
        f"505 Let's celebrate {full_name}, our architect!\n\n",
        f"506 Here's to {full_name}, our engineer!\n\n",
        f"507 Say hello to {full_name}, our developer!\n\n",
        f"508 Let's welcome {full_name}, our programmer!\n\n",
        f"509 Here's {full_name}, our coder!\n\n",
        f"510 All hail {full_name}, our hacker!\n\n",
        f"511 Say hi to {full_name}, our analyst!\n\n",
        f"512 Welcome to the team, {full_name}, our strategist!\n\n",
        f"513 Let's celebrate {full_name}, our planner!\n\n",
        f"514 Here's to {full_name}, our organizer!\n\n",
        f"515 Say hello to {full_name}, our coordinator!\n\n",
        f"516 Let's welcome {full_name}, our manager!\n\n",
        f"517 Here's {full_name}, our leader!\n\n",
        f"518 All hail {full_name}, our supervisor!\n\n",
        f"519 Say hi to {full_name}, our director!\n\n",
        f"520 Welcome to the team, {full_name}, our executive!\n\n",
        f"521 Let's celebrate {full_name}, our CEO!\n\n",
        f"522 Here's to {full_name}, our president!\n\n",
        f"523 Say hello to {full_name}, our chairman!\n\n",
        f"524 Let's welcome {full_name}, our founder!\n\n",
        f"525 Here's {full_name}, our visionary!\n\n",
        f"526 All hail {full_name}, our innovator!\n\n",
        f"527 Say hi to {full_name}, our trailblazer!\n\n",
        f"528 Let's welcome {full_name}, our pioneer!\n\n",
        f"529 Here's {full_name}, our inventor!\n\n",
        f"530 All hail {full_name}, our creator!\n\n",
        f"531 Say hi to {full_name}, our artist!\n\n",
        f"532 Welcome to the team, {full_name}, our designer!\n\n",
        f"533 Let's celebrate {full_name}, our architect!\n\n",
        f"534 Here's to {full_name}, our engineer!\n\n",
        f"535 Say hello to {full_name}, our developer!\n\n",
        f"536 Let's welcome {full_name}, our programmer!\n\n",
        f"537 Here's {full_name}, our coder!\n\n",
        f"538 All hail {full_name}, our hacker!\n\n",
        f"539 Say hi to {full_name}, our analyst!\n\n",
        f"540 Welcome to the team, {full_name}, our strategist!\n\n",
        f"541 Let's celebrate {full_name}, our planner!\n\n",
        f"542 Here's to {full_name}, our organizer!\n\n",
        f"543 Say hello to {full_name}, our coordinator!\n\n",
        f"544 Let's welcome {full_name}, our manager!\n\n",
        f"545 Here's {full_name}, our leader!\n\n",
        f"546 All hail {full_name}, our supervisor!\n\n",
        f"547 Say hi to {full_name}, our director!\n\n",
        f"548 Welcome to the team, {full_name}, our executive!\n\n",
        f"549 Let's celebrate {full_name}, our CEO!\n\n",
        f"550 Here's to {full_name}, our president!\n\n",
        f"551 Say hello to {full_name}, our chairman!\n\n",
        f"552 Let's welcome {full_name}, our founder!\n\n",
        f"553 Here's {full_name}, our visionary!\n\n",
        f"554 All hail {full_name}, our innovator!\n\n",
        f"555 Say hi to {full_name}, our trailblazer!\n\n",
        f"556 Let's welcome {full_name}, our pioneer!\n\n",
        f"557 Here's {full_name}, our inventor!\n\n",
        f"558 All hail {full_name}, our creator!\n\n",
        f"559 Say hi to {full_name}, our artist!\n\n",
        f"560 Welcome to the team, {full_name}, our designer!\n\n",
        f"561 Let's celebrate {full_name}, our architect!\n\n",
        f"562 Here's to {full_name}, our engineer!\n\n",
        f"563 Say hello to {full_name}, our developer!\n\n",
        f"564 Let's welcome {full_name}, our programmer!\n\n",
        f"565 Here's {full_name}, our coder!\n\n",
        f"566 All hail {full_name}, our hacker!\n\n",
        f"567 Say hi to {full_name}, our analyst!\n\n",
        f"568 Welcome to the team, {full_name}, our strategist!\n\n",
        f"569 Let's celebrate {full_name}, our planner!\n\n",
        f"570 Here's to {full_name}, our organizer!\n\n",
        f"571 Say hello to {full_name}, our coordinator!\n\n",
        f"572 Let's welcome {full_name}, our manager!\n\n",
        f"573 Here's {full_name}, our leader!\n\n",
        f"574 All hail {full_name}, our supervisor!\n\n",
        f"575 Say hi to {full_name}, our director!\n\n",
        f"576 Welcome to the team, {full_name}, our executive!\n\n",
        f"577 Let's celebrate {full_name}, our CEO!\n\n",
        f"578 Here's to {full_name}, our president!\n\n",
        f"579 Say hello to {full_name}, our chairman!\n\n",
        f"580 Let's welcome {full_name}, our founder!\n\n",
        f"581 Here's {full_name}, our visionary!\n\n",
        f"582 All hail {full_name}, our innovator!\n\n",
        f"583 Say hi to {full_name}, our trailblazer!\n\n",
        f"584 Let's welcome {full_name}, our pioneer!\n\n",
        f"585 Here's {full_name}, our inventor!\n\n",
        f"586 All hail {full_name}, our creator!\n\n",
        f"587 Say hi to {full_name}, our artist!\n\n",
        f"588 Welcome to the team, {full_name}, our designer!\n\n",
        f"589 Let's celebrate {full_name}, our architect!\n\n",
        f"590 Here's to {full_name}, our engineer!\n\n",
        f"591 Say hello to {full_name}, our developer!\n\n",
        f"592 Let's welcome {full_name}, our programmer!\n\n",
        f"593 Here's {full_name}, our coder!\n\n",
        f"594 All hail {full_name}, our hacker!\n\n",
        f"595 Say hi to {full_name}, our analyst!\n\n",
        f"596 Welcome to the team, {full_name}, our strategist!\n\n",
        f"597 Let's celebrate {full_name}, our planner!\n\n",
        f"598 Here's to {full_name}, our organizer!\n\n",
        f"599 Say hello to {full_name}, our coordinator!\n\n",
        f"600 Let's welcome {full_name}, our manager!\n\n",
        f"601 Here's {full_name}, our leader!\n\n",
        f"602 All hail {full_name}, our supervisor!\n\n",
        f"603 Say hi to {full_name}, our director!\n\n",
        f"604 Welcome to the team, {full_name}, our executive!\n\n",
        f"605 Let's celebrate {full_name}, our CEO!\n\n",
        f"606 Here's to {full_name}, our president!\n\n",
        f"607 Say hello to {full_name}, our chairman!\n\n",
        f"608 Let's welcome {full_name}, our founder!\n\n",
        f"609 Here's {full_name}, our visionary!\n\n",
        f"610 All hail {full_name}, our innovator!\n\n",
        f"611 Say hi to {full_name}, our trailblazer!\n\n",
        f"612 Let's welcome {full_name}, our pioneer!\n\n",
        f"613 Here's {full_name}, our inventor!\n\n",
        f"614 All hail {full_name}, our creator!\n\n",
        f"615 Say hi to {full_name}, our artist!\n\n",
        f"616 Welcome to the team, {full_name}, our designer!\n\n",
        f"617 Let's celebrate {full_name}, our architect!\n\n",
        f"618 Here's to {full_name}, our engineer!\n\n",
        f"619 Say hello to {full_name}, our developer!\n\n",
        f"620 Let's welcome {full_name}, our programmer!\n\n",
        f"621 Here's {full_name}, our coder!\n\n",
        f"622 All hail {full_name}, our hacker!\n\n",
        f"623 Say hi to {full_name}, our analyst!\n\n",
        f"624 Welcome to the team, {full_name}, our strategist!\n\n",
        f"625 Let's celebrate {full_name}, our planner!\n\n",
        f"626 Here's to {full_name}, our organizer!\n\n",
        f"627 Say hello to {full_name}, our coordinator!\n\n",
        f"628 Let's welcome {full_name}, our manager!\n\n",
        f"629 Here's {full_name}, our leader!\n\n",
        f"630 All hail {full_name}, our supervisor!\n\n",
        f"631 Say hi to {full_name}, our director!\n\n",
        f"632 Welcome to the team, {full_name}, our executive!\n\n",
        f"633 Let's celebrate {full_name}, our CEO!\n\n",
        f"634 Here's to {full_name}, our president!\n\n",
        f"635 Say hello to {full_name}, our chairman!\n\n",
        f"636 Let's welcome {full_name}, our founder!\n\n",
        f"637 Here's {full_name}, our visionary!\n\n",
        f"638 All hail {full_name}, our innovator!\n\n",
        f"639 Say hi to {full_name}, our trailblazer!\n\n",
        f"640 Let's welcome {full_name}, our pioneer!\n\n",
        f"641 Here's {full_name}, our inventor!\n\n",
        f"642 All hail {full_name}, our creator!\n\n",
        f"643 Say hi to {full_name}, our artist!\n\n",
        f"644 Welcome to the team, {full_name}, our designer!\n\n",
        f"645 Let's celebrate {full_name}, our architect!\n\n",
        f"646 Here's to {full_name}, our engineer!\n\n",
        f"647 Say hello to {full_name}, our developer!\n\n",
        f"648 Let's welcome {full_name}, our programmer!\n\n",
        f"649 Here's {full_name}, our coder!\n\n",
        f"650 All hail {full_name}, our hacker!\n\n",
        f"651 Say hi to {full_name}, our analyst!\n\n",
        f"652 Welcome to the team, {full_name}, our strategist!\n\n",
        f"653 Let's celebrate {full_name}, our planner!\n\n",
        f"654 Here's to {full_name}, our organizer!\n\n",
        f"655 Say hello to {full_name}, our coordinator!\n\n",
        f"656 Let's welcome {full_name}, our manager!\n\n",
        f"657 Here's {full_name}, our leader!\n\n",
        f"658 All hail {full_name}, our supervisor!\n\n",
        f"659 Say hi to {full_name}, our director!\n\n",
        f"660 Welcome to the team, {full_name}, our executive!\n\n",
        f"661 Let's celebrate {full_name}, our CEO!\n\n",
        f"662 Here's to {full_name}, our president!\n\n",
        f"663 Say hello to {full_name}, our chairman!\n\n",
        f"664 Let's welcome {full_name}, our founder!\n\n",
        f"665 Here's {full_name}, our visionary!\n\n",
        f"666 All hail {full_name}, our innovator!\n\n",
        f"667 Say hi to {full_name}, our trailblazer!\n\n",
        f"668 Let's welcome {full_name}, our pioneer!\n\n",
        f"669 Here's {full_name}, our inventor!\n\n",
        f"670 All hail {full_name}, our creator!\n\n",
        f"671 Say hi to {full_name}, our artist!\n\n",
        f"672 Welcome to the team, {full_name}, our designer!\n\n",
        f"673 Let's celebrate {full_name}, our architect!\n\n",
        f"674 Here's to {full_name}, our engineer!\n\n",
        f"675 Say hello to {full_name}, our developer!\n\n",
        f"676 Let's welcome {full_name}, our programmer!\n\n",
        f"677 Here's {full_name}, our coder!\n\n",
        f"678 All hail {full_name}, our hacker!\n\n",
        f"679 Say hi to {full_name}, our analyst!\n\n",
        f"680 Welcome to the team, {full_name}, our strategist!\n\n",
        f"681 Let's celebrate {full_name}, our planner!\n\n",
        f"682 Here's to {full_name}, our organizer!\n\n",
        f"683 Say hello to {full_name}, our coordinator!\n\n",
        f"684 Let's welcome {full_name}, our manager!\n\n",
        f"685 Here's {full_name}, our leader!\n\n",
        f"686 All hail {full_name}, our supervisor!\n\n",
        f"687 Say hi to {full_name}, our director!\n\n",
        f"688 Welcome to the team, {full_name}, our executive!\n\n",
        f"689 Let's celebrate {full_name}, our CEO!\n\n",
        f"690 Here's to {full_name}, our president!\n\n",
        f"691 Say hello to {full_name}, our chairman!\n\n",
        f"692 Let's welcome {full_name}, our founder!\n\n",
        f"693 Here's {full_name}, our visionary!\n\n",
        f"694 All hail {full_name}, our innovator!\n\n",
        f"695 Say hi to {full_name}, our trailblazer!\n\n",
        f"696 Let's welcome {full_name}, our pioneer!\n\n",
        f"697 Here's {full_name}, our inventor!\n\n",
        f"698 All hail {full_name}, our creator!\n\n",
        f"699 Say hi to {full_name}, our artist!\n\n",
        f"700 Welcome to the team, {full_name}, our designer!\n\n",
        f"701 Let's celebrate {full_name}, our architect!\n\n",
        f"702 Here's to {full_name}, our engineer!\n\n",
        f"703 Say hello to {full_name}, our developer!\n\n",
        f"704 Let's welcome {full_name}, our programmer!\n\n",
        f"705 Here's {full_name}, our coder!\n\n",
        f"706 All hail {full_name}, our hacker!\n\n",
        f"707 Say hi to {full_name}, our analyst!\n\n",
        f"708 Welcome to the team, {full_name}, our strategist!\n\n",
        f"709 Let's celebrate {full_name}, our planner!\n\n",
        f"710 Here's to {full_name}, our organizer!\n\n",
        f"711 Say hello to {full_name}, our coordinator!\n\n",
        f"712 Let's welcome {full_name}, our manager!\n\n",
        f"713 Here's {full_name}, our leader!\n\n",
        f"714 All hail {full_name}, our supervisor!\n\n",
        f"715 Say hi to {full_name}, our director!\n\n",
        f"716 Welcome to the team, {full_name}, our executive!\n\n",
        f"717 Let's celebrate {full_name}, our CEO!\n\n",
        f"718 Here's to {full_name}, our president!\n\n",
        f"719 Say hello to {full_name}, our chairman!\n\n",
        f"720 Let's welcome {full_name}, our founder!\n\n",
        f"721 Here's {full_name}, our visionary!\n\n",
        f"722 All hail {full_name}, our innovator!\n\n",
        f"723 Say hi to {full_name}, our trailblazer!\n\n",
        f"724 Let's welcome {full_name}, our pioneer!\n\n",
        f"725 Here's {full_name}, our inventor!\n\n",
        f"726 All hail {full_name}, our creator!\n\n",
        f"727 Say hi to {full_name}, our artist!\n\n",
        f"728 Welcome to the team, {full_name}, our designer!\n\n",
        f"729 Let's celebrate {full_name}, our architect!\n\n",
        f"730 Here's to {full_name}, our engineer!\n\n",
        f"731 Say hello to {full_name}, our developer!\n\n",
        f"732 Let's welcome {full_name}, our programmer!\n\n",
        f"733 Here's {full_name}, our coder!\n\n",
        f"734 All hail {full_name}, our hacker!\n\n",
        f"735 Say hi to {full_name}, our analyst!\n\n",
        f"736 Welcome to the team, {full_name}, our strategist!\n\n",
        f"737 Let's celebrate {full_name}, our planner!\n\n",
        f"738 Here's to {full_name}, our organizer!\n\n",
        f"739 Say hello to {full_name}, our coordinator!\n\n",
        f"740 Let's welcome {full_name}, our manager!\n\n",
        f"741 Here's {full_name}, our leader!\n\n",
        f"742 All hail {full_name}, our supervisor!\n\n",
        f"743 Say hi to {full_name}, our director!\n\n",
        f"744 Welcome to the team, {full_name}, our executive!\n\n",
        f"745 Let's celebrate {full_name}, our CEO!\n\n",
        f"746 Here's to {full_name}, our president!\n\n",
        f"747 Say hello to {full_name}, our chairman!\n\n",
        f"748 Let's welcome {full_name}, our founder!\n\n",
        f"749 Here's {full_name}, our visionary!\n\n",
        f"750 All hail {full_name}, our innovator!\n\n",
        f"751 Say hi to {full_name}, our trailblazer!\n\n",
        f"752 Let's welcome {full_name}, our pioneer!\n\n",
        f"753 Here's {full_name}, our inventor!\n\n",
        f"754 All hail {full_name}, our creator!\n\n",
        f"755 Say hi to {full_name}, our artist!\n\n",
        f"756 Welcome to the team, {full_name}, our designer!\n\n",
        f"757 Let's celebrate {full_name}, our architect!\n\n",
        f"758 Here's to {full_name}, our engineer!\n\n",
        f"759 Say hello to {full_name}, our developer!\n\n",
        f"760 Let's welcome {full_name}, our programmer!\n\n",
        f"761 Here's {full_name}, our coder!\n\n",
        f"762 All hail {full_name}, our hacker!\n\n",
        f"763 Say hi to {full_name}, our analyst!\n\n",
        f"764 Welcome to the team, {full_name}, our strategist!\n\n",
        f"765 Let's celebrate {full_name}, our planner!\n\n",
        f"766 Here's to {full_name}, our organizer!\n\n",
        f"767 Say hello to {full_name}, our coordinator!\n\n",
        f"768 Let's welcome {full_name}, our manager!\n\n",
        f"769 Here's {full_name}, our leader!\n\n",
        f"770 All hail {full_name}, our supervisor!\n\n",
        f"771 Say hi to {full_name}, our director!\n\n",
        f"772 Welcome to the team, {full_name}, our executive!\n\n",
        f"773 Let's celebrate {full_name}, our CEO!\n\n",
        f"774 Here's to {full_name}, our president!\n\n",
        f"775 Say hello to {full_name}, our chairman!\n\n",
        f"776 Let's welcome {full_name}, our founder!\n\n",
        f"777 Here's {full_name}, our visionary!\n\n",
        f"778 All hail {full_name}, our innovator!\n\n",
        f"779 Say hi to {full_name}, our trailblazer!\n\n",
        f"780 Let's welcome {full_name}, our pioneer!\n\n",
        f"781 Here's {full_name}, our inventor!\n\n",
        f"782 All hail {full_name}, our creator!\n\n",
        f"783 Say hi to {full_name}, our artist!\n\n",
        f"784 Welcome to the team, {full_name}, our designer!\n\n",
        f"785 Let's celebrate {full_name}, our architect!\n\n",
        f"786 Here's to {full_name}, our engineer!\n\n",
        f"787 Say hello to {full_name}, our developer!\n\n",
        f"788 Let's welcome {full_name}, our programmer!\n\n",
        f"789 Here's {full_name}, our coder!\n\n",
        f"790 All hail {full_name}, our hacker!\n\n",
        f"791 Say hi to {full_name}, our analyst!\n\n",
        f"792 Welcome to the team, {full_name}, our strategist!\n\n",
        f"793 Let's celebrate {full_name}, our planner!\n\n",
        f"794 Here's to {full_name}, our organizer!\n\n",
        f"795 Say hello to {full_name}, our coordinator!\n\n",
        f"796 Let's welcome {full_name}, our manager!\n\n",
        f"797 Here's {full_name}, our leader!\n\n",
        f"798 All hail {full_name}, our supervisor!\n\n",
        f"799 Say hi to {full_name}, our director!\n\n",
        f"800 Welcome to the team, {full_name}, our executive!\n\n",
        f"851 Say hello to {full_name}, our coordinator!\n\n",
        f"852 Let's welcome {full_name}, our manager!\n\n",
        f"853 Here's {full_name}, our leader!\n\n",
        f"854 All hail {full_name}, our supervisor!\n\n",
        f"855 Say hi to {full_name}, our director!\n\n",
        f"856 Welcome to the team, {full_name}, our executive!\n\n",
        f"857 Let's celebrate {full_name}, our CEO!\n\n",
        f"858 Here's to {full_name}, our president!\n\n",
        f"859 Say hello to {full_name}, our chairman!\n\n",
        f"860 Let's welcome {full_name}, our founder!\n\n",
        f"861 Here's {full_name}, our visionary!\n\n",
        f"862 All hail {full_name}, our innovator!\n\n",
        f"863 Say hi to {full_name}, our trailblazer!\n\n",
        f"864 Let's welcome {full_name}, our pioneer!\n\n",
        f"865 Here's {full_name}, our inventor!\n\n",
        f"866 All hail {full_name}, our creator!\n\n",
        f"867 Say hi to {full_name}, our artist!\n\n",
        f"868 Welcome to the team, {full_name}, our designer!\n\n",
        f"869 Let's celebrate {full_name}, our architect!\n\n",
        f"870 Here's to {full_name}, our engineer!\n\n",
        f"871 Say hello to {full_name}, our developer!\n\n",
        f"872 Let's welcome {full_name}, our programmer!\n\n",
        f"873 Here's {full_name}, our coder!\n\n",
        f"874 All hail {full_name}, our hacker!\n\n",
        f"875 Say hi to {full_name}, our analyst!\n\n",
        f"876 Welcome to the team, {full_name}, our strategist!\n\n",
        f"877 Let's celebrate {full_name}, our planner!\n\n",
        f"878 Here's to {full_name}, our organizer!\n\n",
        f"879 Say hello to {full_name}, our coordinator!\n\n",
        f"880 Let's welcome {full_name}, our manager!\n\n",
        f"881 Here's {full_name}, our leader!\n\n",
        f"882 All hail {full_name}, our supervisor!\n\n",
        f"883 Say hi to {full_name}, our director!\n\n",
        f"884 Welcome to the team, {full_name}, our executive!\n\n",
        f"885 Let's celebrate {full_name}, our CEO!\n\n",
        f"886 Here's to {full_name}, our president!\n\n",
        f"887 Say hello to {full_name}, our chairman!\n\n",
        f"888 Let's welcome {full_name}, our founder!\n\n",
        f"889 Here's {full_name}, our visionary!\n\n",
        f"890 All hail {full_name}, our innovator!\n\n",
        f"891 Say hi to {full_name}, our trailblazer!\n\n",
        f"892 Let's welcome {full_name}, our pioneer!\n\n",
        f"893 Here's {full_name}, our inventor!\n\n",
        f"894 All hail {full_name}, our creator!\n\n",
        f"895 Say hi to {full_name}, our artist!\n\n",
        f"896 Welcome to the team, {full_name}, our designer!\n\n",
        f"897 Let's celebrate {full_name}, our architect!\n\n",
        f"898 Here's to {full_name}, our engineer!\n\n",
        f"899 Say hello to {full_name}, our developer!\n\n",
        f"900 Let's welcome {full_name}, our programmer!\n\n",
        f"901 Here's {full_name}, our coder!\n\n",
        f"902 All hail {full_name}, our hacker!\n\n",
        f"903 Say hi to {full_name}, our analyst!\n\n",
        f"904 Welcome to the team, {full_name}, our strategist!\n\n",
        f"905 Let's celebrate {full_name}, our planner!\n\n",
        f"906 Here's to {full_name}, our organizer!\n\n",
        f"907 Say hello to {full_name}, our coordinator!\n\n",
        f"908 Let's welcome {full_name}, our manager!\n\n",
        f"909 Here's {full_name}, our leader!\n\n",
        f"910 All hail {full_name}, our supervisor!\n\n",
        f"911 Say hi to {full_name}, our director!\n\n",
        f"912 Welcome to the team, {full_name}, our executive!\n\n",
        f"913 Let's celebrate {full_name}, our CEO!\n\n",
        f"914 Here's to {full_name}, our president!\n\n",
        f"915 Say hello to {full_name}, our chairman!\n\n",
        f"916 Let's welcome {full_name}, our founder!\n\n",
        f"917 Here's {full_name}, our visionary!\n\n",
        f"918 All hail {full_name}, our innovator!\n\n",
        f"919 Say hi to {full_name}, our trailblazer!\n\n",
        f"920 Let's welcome {full_name}, our pioneer!\n\n",
        f"921 Here's {full_name}, our inventor!\n\n",
        f"922 All hail {full_name}, our creator!\n\n",
        f"923 Say hi to {full_name}, our artist!\n\n",
        f"924 Welcome to the team, {full_name}, our designer!\n\n",
        f"925 Let's celebrate {full_name}, our architect!\n\n",
        f"926 Here's to {full_name}, our engineer!\n\n",
        f"927 Say hello to {full_name}, our developer!\n\n",
        f"928 Let's welcome {full_name}, our programmer!\n\n",
        f"929 Here's {full_name}, our coder!\n\n",
        f"930 All hail {full_name}, our hacker!\n\n",
        f"931 Say hi to {full_name}, our analyst!\n\n",
        f"932 Welcome to the team, {full_name}, our strategist!\n\n",
        f"933 Let's celebrate {full_name}, our planner!\n\n",
        f"934 Here's to {full_name}, our organizer!\n\n",
        f"935 Say hello to {full_name}, our coordinator!\n\n",
        f"936 Let's welcome {full_name}, our manager!\n\n",
        f"937 Here's {full_name}, our leader!\n\n",
        f"938 All hail {full_name}, our supervisor!\n\n",
        f"939 Say hi to {full_name}, our director!\n\n",
        f"940 Welcome to the team, {full_name}, our executive!\n\n",
        f"941 Let's celebrate {full_name}, our CEO!\n\n",
        f"942 Here's to {full_name}, our president!\n\n",
        f"943 Say hello to {full_name}, our chairman!\n\n",
        f"944 Let's welcome {full_name}, our founder!\n\n",
        f"945 Here's {full_name}, our visionary!\n\n",
        f"946 All hail {full_name}, our innovator!\n\n",
        f"947 Say hi to {full_name}, our trailblazer!\n\n",
        f"948 Let's welcome {full_name}, our pioneer!\n\n",
        f"949 Here's {full_name}, our inventor!\n\n",
        f"950 All hail {full_name}, our creator!\n\n",
        f"951 Say hi to {full_name}, our artist!\n\n",
        f"952 Welcome to the team, {full_name}, our designer!\n\n",
        f"953 Let's celebrate {full_name}, our architect!\n\n",
        f"954 Here's to {full_name}, our engineer!\n\n",
        f"955 Say hello to {full_name}, our developer!\n\n",
        f"956 Let's welcome {full_name}, our programmer!\n\n",
        f"957 Here's {full_name}, our coder!\n\n",
        f"958 All hail {full_name}, our hacker!\n\n",
        f"959 Say hi to {full_name}, our analyst!\n\n",
        f"960 Welcome to the team, {full_name}, our strategist!\n\n",
        f"961 Let's celebrate {full_name}, our planner!\n\n",
        f"962 Here's to {full_name}, our organizer!\n\n",
        f"963 Say hello to {full_name}, our coordinator!\n\n",
        f"964 Let's welcome {full_name}, our manager!\n\n",
        f"965 Here's {full_name}, our leader!\n\n",
        f"966 All hail {full_name}, our supervisor!\n\n",
        f"967 Say hi to {full_name}, our director!\n\n",
        f"968 Welcome to the team, {full_name}, our executive!\n\n",
        f"969 Let's celebrate {full_name}, our CEO!\n\n",
        f"970 Here's to {full_name}, our president!\n\n",
        f"971 Say hello to {full_name}, our chairman!\n\n",
        f"972 Let's welcome {full_name}, our founder!\n\n",
        f"973 Here's {full_name}, our visionary!\n\n",
        f"974 All hail {full_name}, our innovator!\n\n",
        f"975 Say hi to {full_name}, our trailblazer!\n\n",
        f"976 Let's welcome {full_name}, our pioneer!\n\n",
        f"977 Here's {full_name}, our inventor!\n\n",
        f"978 All hail {full_name}, our creator!\n\n",
        f"979 Say hi to {full_name}, our artist!\n\n",
        f"980 Welcome to the team, {full_name}, our designer!\n\n",
        f"981 Let's celebrate {full_name}, our architect!\n\n",
        f"982 Here's to {full_name}, our engineer!\n\n",
        f"983 Say hello to {full_name}, our developer!\n\n",
        f"984 Let's welcome {full_name}, our programmer!\n\n",
        f"985 Here's {full_name}, our coder!\n\n",
        f"986 All hail {full_name}, our hacker!\n\n",
        f"987 Say hi to {full_name}, our analyst!\n\n",
        f"988 Welcome to the team, {full_name}, our strategist!\n\n",
        f"989 Let's celebrate {full_name}, our planner!\n\n",
        f"990 Here's to {full_name}, our organizer!\n\n",
        f"991 Say hello to {full_name}, our coordinator!\n\n",
        f"992 Let's welcome {full_name}, our manager!\n\n",
        f"993 Here's {full_name}, our leader!\n\n",
        f"994 All hail {full_name}, our supervisor!\n\n",
        f"995 Say hi to {full_name}, our director!\n\n",
        f"996 Welcome to the team, {full_name}, our executive!\n\n",
        f"997 Let's celebrate {full_name}, our CEO!\n\n",
        f"998 Here's to {full_name}, our president!\n\n",
        f"999 Say hello to {full_name}, our chairman!\n\n",
        f"1000 Let's welcome {full_name}, our founder!\n\n",
        # Add more designs here Rana Universe 🍌🍌🍌...
    ]
    
    design_str = random.choice(designs)
    return f"{design_str}"






async def start_cmd_private(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.message.from_user
    text = (
        f"{await get_user_name_design(user, context)}\n"
        f"This is from main start_cmd function"
        f"This is for checking purpose onlu"
    )
    await context.bot.send_message(user.id, text, parse_mode= ParseMode.HTML)




async def extra_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    '''This is execute when any extra /cmd came to bot'''
    user = update.message.from_user
    user_text = update.message.text
    text = f"Hello <b>{user.full_name}</b>, You have Send me <code>{user_text}</code>\n"
    text += f"I dont understand what you want to do with this cmd pls send /help"
    await context.bot.send_message(user.id, text, parse_mode= ParseMode.HTML)


async def echo_fun(update: Update, context: ContextTypes.DEFAULT_TYPE):
    '''This will send the same msg send to the bot'''
    user = update.message.from_user
    text = (f"You have send me This Text Below:\n"
            "Thanks Boss")
    await context.bot.send_message(user.id, text)






def main() -> None:
    """Start the bot."""

    application = Application.builder().token(token).build()



    application.add_handler(CommandHandler(
        command= ["start", "st"],
        callback= start_cmd_private,
        filters= filters.ChatType.PRIVATE,
        block= False
    ))


    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, echo_fun))
    application.add_handler(MessageHandler(filters.Command(), extra_cmd))

    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()







